// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrdKCRL4BfRVJugXzlZCDGT-LRHrAATM',
    appId: '1:223726604961:web:40753956fea978cd8f56e0',
    messagingSenderId: '223726604961',
    projectId: 'folderapp-ee774',
    authDomain: 'folderapp-ee774.firebaseapp.com',
    storageBucket: 'folderapp-ee774.firebasestorage.app',
    measurementId: 'G-CTR8J3DS0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhk1wp9nE9h2_qz7dZeIIS3KK3TW6nRDk',
    appId: '1:223726604961:android:d95c5b4024a5636c8f56e0',
    messagingSenderId: '223726604961',
    projectId: 'folderapp-ee774',
    storageBucket: 'folderapp-ee774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy4QG1-OkVMPk2qQiY1XZobaAhkmBNZyw',
    appId: '1:223726604961:ios:a653eb397d5a57e48f56e0',
    messagingSenderId: '223726604961',
    projectId: 'folderapp-ee774',
    storageBucket: 'folderapp-ee774.firebasestorage.app',
    iosBundleId: 'com.example.myFolderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy4QG1-OkVMPk2qQiY1XZobaAhkmBNZyw',
    appId: '1:223726604961:ios:a653eb397d5a57e48f56e0',
    messagingSenderId: '223726604961',
    projectId: 'folderapp-ee774',
    storageBucket: 'folderapp-ee774.firebasestorage.app',
    iosBundleId: 'com.example.myFolderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZrdKCRL4BfRVJugXzlZCDGT-LRHrAATM',
    appId: '1:223726604961:web:a172c17e0921f20d8f56e0',
    messagingSenderId: '223726604961',
    projectId: 'folderapp-ee774',
    authDomain: 'folderapp-ee774.firebaseapp.com',
    storageBucket: 'folderapp-ee774.firebasestorage.app',
    measurementId: 'G-LFENDFWCQC',
  );
}
